services:
  pocketbase:
    image: monorepo-starter-pocketbase:0.28.4
    build:
      context: packages/backend
    ports:
      - '8080:8080'
    env_file:
      - ./packages/backend/.env
      - ./packages/backend/.env.local
    volumes:
      - ./packages/backend/pb_hooks:/pb/pb_hooks
      - pb-data:/pb/pb_data
    restart: unless-stopped

volumes:
  pb-data:
